### ISSUE TITLE
Adaptar el codigo para que siga lo definido en la API

### ISSUE THREAD

**Issue by ajunge** [rmeb/keyserver#2]
La definicion de la API esta en el README.md

**Comment by ajunge** [comment]
@ocio28 revisa si esta bien y cierras este issue porfa.

**Comment by ajunge** [comment]
Ojo que cambie el nombre del campo en la tabla.
No probe el SQL porque no tengo un postgres a mano

**Comment by ocio28** [comment]
revisado y adaptado.
